server:
  port: 8088
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.121.182:3306/ontheway?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
      # Redis数据库索引（默认为0）
      database: 2
      # Redis服务器地址
#      host: 10.1.1.240
      host: 172.19.121.182
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      # 连接池最大连接数（使用负值表示没有限制）
      jedis:
        pool:
          max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1s
        # 连接池中的最大空闲连接
          max-idle: 8
        # 连接池中的最小空闲连接
          min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 2s
